#!/usr/bin/env python
"""Interactive script to setup Kaggle and HuggingFace credentials.

This script helps users:
1. Input their credentials interactively
2. Create/update the .env file
3. Verify credentials work correctly
"""

import os
import sys
from pathlib import Path
from typing import Optional

# Try to add src to path for imports
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root / "src"))

from cv_ranking_system.credentials import CredentialsManager


def get_input_masked(prompt: str) -> str:
    """Get input from user, optionally masking for sensitive data."""
    try:
        # Try to use getpass for sensitive inputs (API keys)
        import getpass
        if "password" in prompt.lower() or "key" in prompt.lower() or "token" in prompt.lower():
            return getpass.getpass(prompt)
    except (ImportError, Exception):
        pass
    
    return input(prompt)


def setup_kaggle_credentials() -> tuple[Optional[str], Optional[str]]:
    """Interactive setup for Kaggle credentials."""
    print("\n" + "="*60)
    print("KAGGLE SETUP")
    print("="*60)
    print("""
To get your Kaggle credentials:
1. Go to https://www.kaggle.com/settings/account
2. Scroll to API section and click 'Create New API Token'
3. This downloads kaggle.json - open it in a text editor
""")
    
    username = input("Enter Kaggle Username: ").strip()
    if not username:
        print("⚠️  Kaggle username is required. Skipping Kaggle setup.")
        return None, None
    
    api_key = get_input_masked("Enter Kaggle API Key (from kaggle.json): ").strip()
    if not api_key:
        print("⚠️  Kaggle API key is required. Skipping Kaggle setup.")
        return None, None
    
    print(f"✓ Kaggle username set to: {username}")
    return username, api_key


def setup_huggingface_credentials() -> Optional[str]:
    """Interactive setup for HuggingFace credentials."""
    print("\n" + "="*60)
    print("HUGGINGFACE SETUP")
    print("="*60)
    print("""
To get your HuggingFace API token:
1. Go to https://huggingface.co/settings/tokens
2. Click 'New token'
3. Give it a name and select 'read' permission
4. Click 'Create token' and copy the value
""")
    
    token = get_input_masked("Enter HuggingFace API Token (press Enter to skip): ").strip()
    if not token:
        print("⚠️  HuggingFace API token not provided (optional)")
        return None
    
    if token.startswith("hf_"):
        print("✓ HuggingFace token looks valid (starts with 'hf_')")
    else:
        print("⚠️  Warning: Token doesn't start with 'hf_' - please double-check")
    
    return token


def create_env_file(
    env_path: Path,
    kaggle_username: Optional[str],
    kaggle_api_key: Optional[str],
    hf_token: Optional[str],
) -> bool:
    """Create or update .env file with credentials."""
    env_content = f"""# Generated by setup_credentials.py
# Do not commit this file to version control!

# Kaggle API Credentials
KAGGLE_USERNAME={kaggle_username or ""}
KAGGLE_API_KEY={kaggle_api_key or ""}

# HuggingFace API Token
HUGGINGFACE_API_TOKEN={hf_token or ""}

# Alternative HuggingFace token variable (optional)
# HF_TOKEN={hf_token or ""}
"""
    
    try:
        # Check if file exists
        if env_path.exists():
            response = input(f"\n.env file already exists at {env_path}. Overwrite? (y/n): ").strip().lower()
            if response != 'y':
                print("⚠️  .env file not updated")
                return False
        
        # Write file
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        # Set proper permissions (Unix-like systems)
        try:
            env_path.chmod(0o600)  # Read/write only by owner
        except (OSError, NotImplementedError):
            # Windows doesn't support chmod
            pass
        
        print(f"\n✓ .env file created/updated at: {env_path}")
        return True
    
    except Exception as e:
        print(f"\n✗ Error writing .env file: {e}")
        return False


def verify_credentials(env_path: Path) -> bool:
    """Verify that credentials are working."""
    print("\n" + "="*60)
    print("VERIFYING CREDENTIALS")
    print("="*60)
    
    try:
        # Create a new credentials manager
        creds_manager = CredentialsManager(env_file=str(env_path))
        
        # Check status
        status = creds_manager.get_status()
        
        print(f"\n.env file: {status['env_file']}")
        
        # Check Kaggle
        if status['kaggle']['configured']:
            if status['kaggle']['valid']:
                print(f"✓ Kaggle credentials valid (user: {status['kaggle']['username']})")
            else:
                print("✗ Kaggle credentials configured but invalid")
        else:
            print("○ Kaggle credentials not configured")
        
        # Check HuggingFace
        if status['huggingface']['configured']:
            if status['huggingface']['valid']:
                print("✓ HuggingFace credentials valid")
            else:
                print("✗ HuggingFace credentials configured but invalid")
        else:
            print("○ HuggingFace credentials not configured")
        
        # Try to setup auth
        results = creds_manager.setup_all_auth()
        print(f"\nAuthentication setup results: {results}")
        
        return True
    
    except Exception as e:
        print(f"\n✗ Error verifying credentials: {e}")
        return False


def main():
    """Main setup function."""
    print("\n" + "="*60)
    print("CV Ranking System - Credentials Setup")
    print("="*60)
    
    # Determine .env path
    env_path = Path.cwd() / ".env"
    if not env_path.parent.exists():
        # Try project root
        env_path = Path(__file__).parent / ".env"
    
    print(f"\n.env file location: {env_path}")
    
    # Ask what to do
    print("\nWhat would you like to do?")
    print("1. Setup new credentials")
    print("2. Verify existing credentials")
    print("3. Update existing credentials")
    print("4. Exit")
    
    choice = input("\nSelect option (1-4): ").strip()
    
    if choice == "1":
        # Setup new credentials
        print("\nSetting up new credentials...")
        
        kaggle_username, kaggle_api_key = setup_kaggle_credentials()
        hf_token = setup_huggingface_credentials()
        
        if not any([kaggle_username, hf_token]):
            print("\n⚠️  No credentials provided")
            return
        
        if create_env_file(env_path, kaggle_username, kaggle_api_key, hf_token):
            verify_credentials(env_path)
    
    elif choice == "2":
        # Verify existing credentials
        verify_credentials(env_path)
    
    elif choice == "3":
        # Update credentials
        print("\nUpdating credentials...")
        
        # Load existing
        try:
            existing_manager = CredentialsManager(env_file=str(env_path))
            existing_kaggle = existing_manager.get_kaggle_credentials()
            existing_hf = existing_manager.get_huggingface_credentials()
            
            print(f"\nExisting Kaggle user: {existing_kaggle.username if existing_kaggle else 'None'}")
            print(f"Existing HuggingFace token: {'Yes' if existing_hf else 'No'}")
        except Exception as e:
            print(f"\nCould not read existing credentials: {e}")
            existing_kaggle = None
            existing_hf = None
        
        # Get new credentials
        kaggle_username, kaggle_api_key = setup_kaggle_credentials()
        hf_token = setup_huggingface_credentials()
        
        if create_env_file(env_path, kaggle_username, kaggle_api_key, hf_token):
            verify_credentials(env_path)
    
    elif choice == "4":
        print("\nExiting...")
    
    else:
        print("\n✗ Invalid option")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Unexpected error: {e}")
        sys.exit(1)
